In [ ]:
# Install extra packages: uncomment if in google collab

!pip install holoviews
!pip install hvplot

### Recitation 2: Logic gates and information theory. 

> The goal of this tutorial is to get you geared up for solving the homework in an efficient manner using python. We'll learn how to compute mutual information between two discrete random variables using numpy. 

#### Introduction

Information theory is the mathematical theory that aims to describes how to communicate efficiently (with low error and at a fast rate) through an imperfect channel. As we've seen in class, this is a major tool for analyzing biological systems, since it provides a way to quantify the non-linear coupling between random variables. During this tutorial, we will cover some of the concepts central to information theory and how to compute them using python. 

There is a very interesting history about how information theory came about, with big contributions from the ["Young Turks"](https://en.wikipedia.org/wiki/Young_Turks_(Bell_Labs)), a group of scientists and mathematicians working at Bell Labs. Of utmost importance, Claude Shannon, developed the foundations in a landmark paper titled [A Mathematical Theory of Communication](http://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf). I highly recommend for you to read it, as it is a beautiful display of probabilistic and mathematical thinking. 

In this paper, Shannon defined the surprise (or information gain) of learning that an event $x$ with probability $p(x)$ will occur as:

$$
\text{surprise / self-information (x)} = \mathrm{log}_2 \left( \frac{1}{p(x)} \right)
$$

This quantity is measured in a unit called bits. Low-probability events will have high surprise, while an event that has probability 1 of occurring has zero surprise. The $\mathrm{log}$ is there so that if we observe multiple events, the total surprise is additive. The $\mathrm{log}$ is abse 2 so that if we learn that an event with probability $\frac{1}{2}$ happened, the surprise is 1 (we'll calculate this later on), we gain 1 bit of information. 



#### Entropy is the average surprise of learning a random variable

As we saw in class, for a discrete r.v. $X$ that takes values $x_1, x_2, ...,x_n$ with probabilities $p_1, p_2, ..., p_n$ with $\sum_{i} P(X = x_i) = \sum_i^n p_i = 1$, the entropy of X is defined as the expected or average surprise of learning the value of X: 

$$
H(X) = \mathbb{E}_X \left[ \mathrm{log_2} \, \left( \frac{1}{P(X)} \right) \right] \\[1.4em]
= \sum_{i = 1}^n p_i \, \mathrm{log_2}\, \left( \frac{1}{p_i} \right)\\[1.2em]
= - \sum_{i=1}^n  p_i \, \mathrm{log_2} \, \left( p_i \right)
$$

Where the second equality arises from evaluating the formula of the generalized expectation or [law of unconscious statistician (LOTUS)](https://en.wikipedia.org/wiki/Law_of_the_unconscious_statistician). **Note that the entropy doesn't depend on the values the random variable takes, but only on the probability values !**

Let's visualize the entropy for a binary random variable. 

In [ ]:
import numpy as np
import pandas as pd 
import itertools as it
import matplotlib.pyplot as plt
import holoviews as hv
import string
import seaborn as sns 

sns.set_style('dark')
hv.extension('bokeh')

#%load_ext blackcellmagic
%config InlineBackend.figure_format = 'retina'

Exercise: write down a function that returns the entropy of a Bernoulli random variable. 

In [ ]:
def binary_entropy(p):
    "Returns the entropy of a Bernoulli r.v. with probability p"
    
    #Write your code here
    entropy = 
    
    return entropy

In [ ]:
# Test the function ! 
binary_entropy(0.1)

We can see that our function works. Now let's see if it actually returns the right values by calculating the entropy by hand. 

The entropy of a Bernoulli random variable with probability of success $p = 0.5$ is  : 

$$
H(X) = \mathbb{E}_X (- \mathrm{log} \, P(X)) \\[1.4em]
= \sum_{x \in \{0,1 \}} P(X=x) \,  \mathrm{log}_2 \, \left(\frac{1}{P(X = x)} \right)\\[1em]
= P(X = 0) \times \mathrm{log_2} \frac{1}{P(X = 0)} + P(X = 1) \times \mathrm{log_2} \frac{1}{P(X = 1)}\\[1em]
= \frac{1}{2} \times \mathrm{log_2} (2) + \frac{1}{2} \times \mathrm{log_2} (2)\\[1em]
\mathrm{log_2}(2) = 1
$$

Let's see if we do get the answer. 

In [ ]:
# Should return 1
binary_entropy(0.5)

Let's define a set of values for different probabilities $p_i$, and plot the resulting curve.

In [ ]:
# Define an array of probability of success of 
# Bernoulli r.v.s
ps = np.linspace(0, 1, 20)

In [ ]:
# Initalize list 
entropies = []

for p in ps: 
#

Whoa, we got an error! Let's inspect the binary entropy arrays. 

In [ ]:
# Take a look 
binary_entropy

We can see that we got a Not-a-Number (NaN) value when we evaluate `binary_entropy()` with `p` = 0 and `p` = 1.

In [ ]:
#We need to avoid this! 
np.log2(0)

Exercise: Write a function that returns the entropy for a random variable 

In [ ]:
ps = np.array([0.5, 0.5, 0])

In [ ]:
ps[np.nonzero(ps)]

In [ ]:
def entropy(ps): 
    
    # Get nonzero indices
    nz = 

    # Compute entropy for nonzero indices
    entropy = 
    
    return entropy

In [ ]:
entropy(ps)

Let's make an array of probabilities. 

In [ ]:
# Intialize empty array
p_ = #

q_ = #

ps = np.hstack([p_.reshape(-1,1), q_.reshape(-1,1)])

Let's re-evaluate the entropies

In [ ]:
entropies = []

for i in range(len(ps)): 



We can see that we got no error back. 

In [ ]:
entropies

Let's plot the entropies ! 

In [ ]:
hv.extension('bokeh')
entropy_plot = hv.Curve((p_success, entropies)).opts(
    title="Bern(p) entropy", xlabel="probability of success", ylabel="entropy", color = 'salmon', 
    padding = 0.1
)

entropy_plot

Does this plot ring a bell ? In lecture we saw that the variance of a Bernoulli random variable is $p(1-p)$. Let's quickly make a function of this formula and plot the variances for the $p_i$.

In [ ]:
def variance_bernoulli(p): 
    return p*(1-p)

In [ ]:
variances = [  ]

In [ ]:
variance_plot = hv.Curve((p_success, variances)).opts(
    title="Bern(p) variance", xlabel="probability of success", ylabel="entropy", color = 'dodgerblue', 
    padding = 0.1
)

In [ ]:
hv.extension('bokeh')
variance_plot

In [ ]:
hv.extension('bokeh')
variance_plot + entropy_plot

### Quantifying information from coupled random variables 


Remember that the goal of this tutorial is to get you ready for computing the mutual information of noisy logic gates. In order to do so we have define a couple more concepts in order to make this tutorial self-contained. 

#### The Kullback - Leibler divergence quantifies the *distance* between distributions.

Building up towards the mutual information, an important metric to fully grasp the concepts is the Kullback-Leibler (KL) divergence. It is a metric that quantifies the distance between two probability distributions. Let $\mathbf{q} = (q_1, q_2, ..., q_n)$ and $\mathbf{p} = (p_1, p_2, .., p_n)$ be two discrete PMFs. The KL divergence between $\mathbf{q}$ and $\mathbf{p}$ is defined as: 



$$
\text{D}( \mathbf{q} || \mathbf{p} ) = \sum_j q_j \mathrm{log} \left( \frac{1}{p_j} \right)- \sum_j q_j \mathrm{log} \left(\frac{1}{q_j} \right)
$$


This metric thus represents the difference between the average surprise we will experience when the actual probabilities are $\mathbf{q}$ but we are instead using $\mathbf{p}$ as our current guess for $\mathbf{q}$  and the average surprise of  $\mathbf{q}$. 

The intuition is that because, we're using $\mathbf{p}$ as a proxy for $\mathbf{q}$, the term on the left $\mathbb{E}_q [ \mathrm{log_2} (1 / p)]$ will always be higher than the entropy of the true variable $\mathbb{E}_q [ \mathrm{log_2} (1 / q)]$. In other words, we will always be at least as surprised or more when working with an estimate of the true distribution that with the true distribution itself. There is a neat way to prove that the KL divergence is nonnegative using one of the most important inequalities in stats: the Jensen Inequality.

#### Brief detour: Jensen's inequality 

Let $X$ be a random variable. If $g$ is a convex function (in the sense that $g''(x) > 0$), then 

$$
\mathbb{E}(g(X)) > g ( \mathbb{E} (X))
$$

if $g$ is a concave function, then the equality flips. Here is are some intuitive examples of Jensen's inequality. 

 
\mathrm{Var} (x) = \mathbb{E} (x^2) - \mathbb{E} (x)^2. \\[.8em]
\text{because } \mathrm{Var}(x) \ge 0 \\[.8em]
\mathbb{E}(x^2) \ge (\mathbb{E}(x))^2 \\[.8em]
\text{reciprocally because log is a concave function}  \\[.7em]
\mathbb{E}(\mathrm {log}(x)) \le  \mathrm \log \left(\mathbb{E} (X) \right)
$$

#### Conditional entropy

Like conditional probabilities, we can have conditional entropies. The conditional entropy $H(X|Y)$ is the information you gain from observing a random variable $X$ conditioning on knowing the values of another random variable $Y$. Another way to think of the conditional entropy is as the average surprise of the conditional distribution $P(X | Y)$ after observing the distribution $P(Y)$.

The conditional entropy is defined as : 

$$
H(X | Y) = \mathbb{E}_{P(y) } \left[ - \mathrm{log_2} P(X | Y) \right] = - \sum_{y \in Y} P(Y = y) \, \mathrm{log}_2 \, P(X | Y = y)  
$$

Similarly, the conditional entropy $H(Y|X)$ can be written as: 

$$
H(Y|X)  = \mathbb{E}_{P(X)} \left[ - \mathrm{log_2} \, P(Y|X) \right]
$$

Using both of this notions, we can finally now define the mutual information. 

#### Mutual information 

The mutual information of two discrete random variables $X$, $Y$ ($\text{I(X,Y)}$) is the reduction in uncertainty of a random variable $X$ when get to know see the conditional distribution with another r.v. $(X|Y)$. Congruent with this notion, the mutual information is defined as:

$$
\text{I(X,Y)} = \text{H} (X) - \text{H}(X|Y) = \text{H} (Y) - \text{H} (Y | X)
$$

Where $\text{H}(X)$ is the entropy of $X$. A common way to visualize the concepts of entropy, conditional entropy and mutual information is the following: 

In [ ]:
from IPython.display import Image

In [ ]:
Image(
    url = 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Conditional_entropy.png',
    format = 'png',
    width = 500,
    height = 500
)

#### The mutual information is the KL divergence between the joint and the marginal distributions. 

We know that by definition, the mutual information between two discrete random variables is the KL divergence between the joint and the marginal distributions, i.e.: 
$$
\text{MI(X,Y)} = \sum_{y \in Y} \sum_{x \in X} P_{X,Y}(x, y) \,  \mathrm{log_2} \left( \frac{P_{X,Y}(x,y)}{P_{X}(x)P_Y(y))} \right)
$$

This is a nice conceptual version, because we can see that in the limit where the joint and the marginal distributions are equal, i.e., the r.v.s X and Y are independent, the mutual information is close to zero.



#### Brief detour: the Law of Total probability and the marginal distribution

![LOTP](../../figs/LOTP.png)

The Law of Total Probability states that the probability of disjoint events: 

$$
P(B) = \sum_{i} P(B \cap A_i) =  \sum_{i} P(B|A_i)P(A_i)\\[1em]
\text{a particular case is} \\
P(B) = P(B | A) P(A) + P(B | A^c) P(A^c)
$$



Here's an example that we'll see in a bit. 

![joint](../../figs/p_xy.png)

![px](../../figs/px_marg.png)

![px](../../figs/py_marg.png)

![cond](../../figs/p_cond.png)



### Applying mutual information on the english language. 

We'll use an example Shannon used in his paper to estimate the redundancy of letters in the English language using information theory concepts. 

In [ ]:
import toolz as tz
from toolz import curried as c
from collections import Counter
import itertools as it
import unicodedata
import re
from urllib.request import urlretrieve

In [ ]:
url= 'https://raw.githubusercontent.com/thomsonlab/bi195_tutorials/main/data/california_love.txt'

In [ ]:
fname = 'california_love.txt'

In [ ]:
urlretrieve(url, fname)

In [ ]:
! head -10 california_love.txt

 This uses on-memory filtering, so this function alone makes three passes to the data. Caution is neeeded 

In [ ]:
def not_empty_line(line):
    return len(re.sub('[^A-Za-z]', '', line.strip().lower())) > 0

In [ ]:
def read_file(path_to_file): 
    """
    Return a list of strings from a text file.
    """
    with open(path_to_file, 'r') as f: 
        corpus = f.readlines()

    # Remove empty lines 
    corpus = list(filter(not_empty_line, corpus))
    
    # Substitute all symbols not in the alphabet 
    # and lowercase all words 
    corpus = [re.sub('[^A-Za-z]', ' ', line.strip().lower()) for line in corpus]
    
    return corpus

In [ ]:
lines = read_file(fname)

In [ ]:
all_lines = ' '.join(lines)

In [ ]:
all_lines[:100]

In [ ]:
len(all_lines)

In [ ]:
alphabet= set(all_lines)

In [ ]:
alphabet_letters = sorted(list(alphabet))[1:]

In [ ]:
alphabet_letters[:10]

In [ ]:
len(alphabet_letters)

In [ ]:
def process_text(text): 
    "Substitutes symbols in a string with a space."
    text = re.sub('[^A-Za-z]', ' ', text.strip().lower())
    return text

In [ ]:
def stream_file(fname):
    ""
    with open(fname) as f:
        for line in f:
            yield line

In [ ]:
next(stream_file(fname))

In [ ]:
g = stream_file(fname)

In [ ]:
not_empty_line(next(g))

I've created a function that allows us to stream large files and get kmer counts already, so we can just go ahead and apply it to large datasets (see exercise at the final of the notebook).

In [ ]:
def get_counts_kmer_streaming(path_to_file, k=1): 
    """
    Returns a dictionary of kmer counts using streaming.
    This function is designed to handle large files on-disk.
    
    Params 
    ------
    path_to_file(str):
        Path to the file to process. 
    
    k(int, default = 1):
        Size of the k-mer. 
        
    Returns 
    -------
    dict:
        A dictionary whose keys are unique k-mers found in the file 
        and values are the frequencies of appearance. 
    """
    
    return tz.pipe(
        path_to_file,
        stream_file, # Initializes line generator 
        c.filter(not_empty_line), # Gets lines with strings (not symbols or whitespaces)
        c.map(process_text), # Eliminate symbols 
        c.map(str.strip), # Eliminate white space at the end of line
        c.map(str.split), # Split into words
        tz.concat, # Concatenate word iterator
        c.map(c.sliding_window(k)), # Make k-mer tuples
        tz.concat, # Concatenate tuple iterator
        c.map(''.join), # Unpack tuples 
        tz.frequencies # Get kmer frequencies
    )

In [ ]:
counts = get_counts_kmer_streaming(fname, k = 2)

In [ ]:
counts

In [ ]:
alphabet_letters = sorted(list(set(''.join(list(counts.keys())))))

In [ ]:
n_letters = len(alphabet_letters)

In [ ]:
# Get total counts
total_counts = sum(counts.values())

In [ ]:
total_counts

In [ ]:
# Sort freqs by alphabetical order 
freqs = sorted(counts.items(), key = lambda x: x[0])

In [ ]:
#counts

In [ ]:
freqs[:10]

In [ ]:
alphabet_dict = dict(zip(alphabet_letters, np.arange(n_letters)))

alphabet_dict

In [ ]:
bigram_pairs = list(it.product(alphabet_letters, alphabet_letters))

In [ ]:
bigram_pairs[0]<

In [ ]:
position_dict = {
    (str(i + j)): (alphabet_dict[i], alphabet_dict[j]) for (i,j) in bigram_pairs
}

In [ ]:
position_dict[('aa')]

In [ ]:
position_dict[('ie')]

In [ ]:
freqs[:10]

In [ ]:
# Initialize joint distribution matrix 
joint_distro = np.zeros((n_letters,n_letters))

for bigram, counts in freqs: 
    
    # Get indices for given bigram
    index = position_dict[bigram]
    
    # Set counts in array 
    joint_distro[index] = counts

In [ ]:
joint_distro = joint_distro / total_counts

In [ ]:
# Double check normalization condition 
joint_distro.sum()

In [ ]:
len(alphabet_letters)

In [ ]:
df_joint= pd.DataFrame(
    joint_distro, 
    index = pd.Index(list(alphabet_letters), name = 'first letter'),
    columns = pd.Index(list(alphabet_letters), name = 'second letter')
)

In [ ]:
# Take a look 
df_joint

Let's drop columns and rows with nonzero values. 

In [ ]:
(df_joint != 0 ).any(axis  = 0)

In [ ]:
(df_joint != 0 ).any(axis  = 1)

In [ ]:
col_selector = (df_joint != 0).any(axis  = 0)
row_selector = (df_joint != 0).any(axis  = 1)

In [ ]:
row_selector

In [ ]:
df_sel = df_joint.loc[row_selector, col_selector]

In [ ]:
df_melt = df_sel.unstack().reset_index().rename(columns = {0 : 'P(x,y)'})

In [ ]:
import hvplot.pandas

In [ ]:
df_melt.head()

In [ ]:
hv.extension('bokeh')

df_melt.hvplot.heatmap(
    x = 'first letter',
    y = 'second letter', 
    C = 'P(x,y)',
    height = 500,
    width = 600, 
    cmap = 'viridis', 
    title = 'Joint distribution P(x,y)'
)

With the joint distribution in place, we can calculate the entropy of the letters in english.

In [ ]:
#Now let's compute the mutual information between the first and second letters.

p_x = df_sel.values.sum(axis = 1)
p_y = df_sel.values.sum(axis = 0)

In [ ]:
entropy(p_x)

This is indeed what's reported ([see F1 in this post](https://cs.stanford.edu/people/eroberts/courses/soco/projects/1999-00/information-theory/entropy_of_english_9.html) and [Shannon's paper on English language redundancy](https://www.princeton.edu/~wbialek/rome/refs/shannon_51.pdf)).

This is super interesting, but **how do we know if this entropy is a lot or a little? In other words, what would be a null model for the entropy of a distribution?**.


###### Proposition : the uniform distribution is the  distribution with maximum entropy

Intuititively, we can assert that the above proposition is true because, if a uniform distribution every value is equally likely, and thus whichever value we see sampled, will be "surprising". On the other hand, if we think of a very sharp peaked distribution, with the probability mass concentrated about the mean, we would expect that if we sample from the distribution, we would get values close to the mean, and thus, these samples wouldn't be surprising. 

*Proof:* Let $X$~DUnif(0,n) so that every value $P(x = i) = \frac{1}{n}$ for $0 \le i \le n$ : 

$$
H(X) = \mathbb{E} \left[\mathrm{log_2} \left( \frac{1}{p(x)} \right) \right] = \sum_i^n \frac{1}{n} \mathrm{log_2} (n) = \mathrm{log_2 } (n)
$$

Now, let $Y$ be an r.v. that takes on values $ \frac{1}{p_1}, ..., \frac{1}{p_n} $ with probabilities $p_1, .., p_n$. Then $H(Y) = \sum_i^n p_i \mathrm {log} (1 / p_i) = \mathbb{E}[ \mathrm{log} Y]$ by evaluating $Y$ and using LOTUS. By Jensen's : 

$$
H(Y) = \mathbb{E}[ \mathrm{log} Y]  \le \mathrm{log} (\mathbb{E}(Y)) = \mathrm{log} (n) = H(X)
$$

Because the entropy of a random variable doesn't depend on its support (i.e. the values the r.v. takes), then $Y$ is unchanges if we change the support from $p_1, .., p_n$ to $a_1, ..., a_n$ . Therefore $X$ which is uniform has entropy at least as large as that of any other r.v. with support on $a_1, a_2, ..., a_n$. 

#### Redundancy is the ratio that one can compress a random variable

With the notion that the uniform distribution is the one distribution with maximum entropy, the information redundancy of a random variable is defined as: 

$$
\text{redundancy}= 1 - \frac{H(X) }{H_{ \text{unif}}} = 1 - \frac{H(X)}{\mathrm{log_2} n}
$$

where $n$ is taken as as the size of the alphabet. 

We can now compute the information redundancy of english letters !

In [ ]:
entropy(p_x)

In [ ]:
entropy(p_x) / np.log2(26)

In [ ]:
np.log2(26)

In [ ]:
redundancy = 1 - (entropy(p_x)/ np.log2(26))
print(f'The redundancy of the english letters is { round(100*redundancy, 2) } %' )

Shannon, indeed a different and very ingenious way of calculating the entropy of the letters in english, by estimating the entropy over words. Let's continue with our calculations. 

Conditional distributions have to follow all of the properties of distributions, that is, have nonnegative probabilities and sum to one. We can thus then get the conditional distributions by normalizing the joint distribution over rows and columns. 

In [ ]:
df_sel.head()

In [ ]:
joint_distro_filt = df_sel.values

In [ ]:
# Normalize over rows
p_ygx = (joint_distro_filt / p_x.reshape(-1, 1))

# Normalize over columns
p_xgy = joint_distro_filt / p_y

In [ ]:
df_xgy = df_sel.div(df_sel.sum(axis=0), axis = 1)

df_ygx = df_sel.div(df_sel.sum(axis=1), axis = 0)

In [ ]:
# Check that both methods match
np.all(df_xgy.values ==p_xgy)

In [ ]:
# Check that conditional distributions sum to 1
p_xgy.sum(axis = 0) # over columns
p_ygx.sum(axis = 1) # over rows

Now we need a clever way to compute the conditional entropy from our array directly. 

In [58]:
def element_wise_information(px):
    """
    Returns a numpy array with element wise information calculated as -log_2(p_i).
    This quantity is also know as information or self-information:
    https://en.wikipedia.org/wiki/Information_content
    
    Params
    ------
    px (np.array)
        Array of individual probabilities, i.e. a probability vector or distribution.
    
    Returns
    -------
    information (np.array)
        Array of element-wise information content.
    """
    if isinstance(px, list):
        px = np.array(px)
        
    # Make a copy of input array
    information_content = px.copy()
    
    # Get indices of nonzero probability values
    nz = np.nonzero(information_content)
    
    # Compute -log_2(p_i) element-wise
    information_content[nz] *= - np.log2(information_content[nz])
    
    return information_content

In [ ]:
h_x = entropy(p_x)

In [ ]:
h_xgy = np.sum(p_y * element_wise_information(p_xgy))

In [ ]:
h_xgy

In [ ]:
# Mutual information, finally!!
mi = entropy(p_x) - h_xgy

In [ ]:
mi

In [ ]:
h_y = entropy(p_y)

In [ ]:
# Joint entropy 
h_xy = h_x  + h_y - mi 

In [ ]:
h_xy

In [ ]:
redundancy_bigram = 1 - h_xy / np.log2(27**2)

print(f'The information redundancy of bigrams is {round(redundancy_bigram*100, 2) } %')

### Brief on logic gates 

Let's start by making a binary sequence. 

In [1]:
import numpy as np 
import itertools as it

In [2]:
x = (0,1)

In [3]:
x

(0, 1)

We can get all combinations of 0 and 1 by taking the cartesian product. 

In [6]:
xy = np.array(list(it.product(x,x)))

In [12]:
xy

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

Now let's define a new vector storing all of the values evaluating the function OR(X,Y).

In [16]:
# Initialize array
or_expression = np.zeros(xy.shape[0])

# Evaluate OR gate
for ix in range(xy.shape[0]):
    # Unpack each row 
    x, y = xy[ix]
    
    # Evaluate x OR y
    or_expression[ix] = x | y

The expressions for AND and XOR are `&` and `^` respectively. You can read about how to implement more logic functions [here](https://www.journaldev.com/42242/logic-gates-in-python).

In [18]:
# Check it out 
or_expression

array([0., 1., 1., 1.])

In [19]:
or_expression.reshape(-1,1).shape

(4, 1)

In [20]:
or_truth_table = np.hstack([xy, or_expression.reshape(-1, 1)]).astype(int)

In [21]:
or_truth_table

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [24]:
import pandas as pd

In [25]:
or_df = pd.DataFrame(
    or_truth_table, 
    columns = ['x', 'y', 'z (OR)']
)

In [26]:
or_df

x  y  z (OR)
0  0  0       0
1  0  1       1
2  1  0       1
3  1  1       1

Let's start by getting the joint distribution $P(x,z)$.

In [27]:
contingency_table = np.zeros((2,2))

In [29]:
x = or_df['x'].values
z = or_df['z (OR)'].values

In [30]:
x

array([0, 0, 1, 1])

In [31]:
z

array([0, 1, 1, 1])

In [33]:
or_df

x  y  z (OR)
0  0  0       0
1  0  1       1
2  1  0       1
3  1  1       1

In [32]:
(x == 0) & (z == 0)

array([ True, False, False, False])

In [34]:
np.sum((x == 0) & (z == 0))

1

In [35]:
contingency_table

array([[0., 0.],
       [0., 0.]])

In [36]:
for i in [0,1]:
    for j in [0,1]:
        contingency_table[i,j] = np.sum((x == i) & (z == j))

In [37]:
contingency_table

array([[1., 1.],
       [0., 2.]])

In [ ]:
contingency_table = np.zeros((2,2))

In [ ]:
for i,j in zip(x,z):
    contingency_table[i,j] +=1

In [40]:
contingency_table / 4

array([[0.25, 0.25],
       [0.  , 0.5 ]])

In [41]:
p_xz = contingency_table/ contingency_table.sum()

In [42]:
p_xz

array([[0.25, 0.25],
       [0.  , 0.5 ]])

In [43]:
df_joint = pd.DataFrame(
    p_xz, 
    index = pd.Index(['x = 0', 'x = 1']),
    columns = pd.Index(['z = 0', 'z = 1'])
)

In [44]:
df_joint

z = 0  z = 1
x = 0   0.25   0.25
x = 1   0.00   0.50

In [45]:
df_joint.sum(axis = 'rows')

z = 0    0.25
z = 1    0.75
dtype: float64

In [46]:
df_joint.sum(axis = 'columns')

x = 0    0.5
x = 1    0.5
dtype: float64

$P(X | Z ) = \frac{P(X, Z)}{P(Z)}$

In [47]:
df_joint

z = 0  z = 1
x = 0   0.25   0.25
x = 1   0.00   0.50

In [49]:
p_z = df_joint.sum(axis = 'rows').values

In [50]:
p_z

array([0.25, 0.75])

In [55]:
df_joint

z = 0  z = 1
x = 0   0.25   0.25
x = 1   0.00   0.50

In [56]:
p_z

array([0.25, 0.75])

$$
H(X) =  - \sum_i p_i \mathrm{log_2}{p_i}
$$

In [61]:
p_z

array([0.25, 0.75])

In [64]:
log_pz  = np.log2(p_z)
log_pz

array([-2.       , -0.4150375])

In [66]:
np.sum( - p_z*log_pz)

0.8112781244591328

In [67]:
p_x = np.array([0.8, 0.2, 0])

In [68]:
nz = np.nonzero(p_x)

In [70]:
p_x[nz]

array([0.8, 0.2])

In [71]:
def entropy(px):
    
    # Get the nonzero indices 
    nz = np.nonzero(px)
    
    entropy = np.sum(- px[nz] * np.log2(px[nz]))
    
    return entropy 

In [51]:
# P(X | Z) = P(X,Z) / P(Z)
p_xgz = df_joint.values / p_z 

In [72]:
p_xgz

array([[1.        , 0.33333333],
       [0.        , 0.66666667]])

In [73]:
df_joint

z = 0  z = 1
x = 0   0.25   0.25
x = 1   0.00   0.50

In [76]:
p_x = df_joint.sum(axis = 1).values

In [78]:
p_x.shape

(2,)

In [79]:
p_x.reshape(2, 1)

array([[0.5],
       [0.5]])

In [80]:
p_zgx = df_joint.values / p_x.reshape(2,1 )

In [84]:
df_joint

z = 0  z = 1
x = 0   0.25   0.25
x = 1   0.00   0.50

In [85]:
or_df

x  y  z (OR)
0  0  0       0
1  0  1       1
2  1  0       1
3  1  1       1

In [86]:
element_wise_information?

In [88]:
p_x

array([0.5, 0.5])

In [89]:
# H (Z | X )
h_zgx = np.sum(p_x * element_wise_information(p_zgx))

$$
H(Z | X) = -  \sum_{X} P(X) \,\mathrm{log_2} P(Z | X)
$$

In [92]:
h_z = entropy(p_z)

In [93]:
h_z

0.8112781244591328

In [94]:
# MI = H(Z)  - H( Z | X )
mi = h_z - h_zgx

In [95]:
mi

0.31127812445913283

#### The end

This is the end... my only friend, the end. 